Vagrant.configure("2") do |config|
    
    config.vm.define "proxy" do |proxy|
      proxy.vm.box = "bento/ubuntu-22.04"
      proxy.vm.network "private_network", ip: "192.168.44.10"
      proxy.vm.synced_folder "./public", "/var/www/html"
      proxy.vm.provision "shell", path: "bootstrap.sh"
    end
  end
  